# Generated by Django 4.2.1 on 2023-06-07 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_merge_20230606_1829'),
        ('main_app', '0009_merge_20230606_1928'),
    ]

    operations = [
    ]
