# Generated by Django 4.2.1 on 2023-06-07 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_merge_20230607_1535'),
        ('main_app', '0010_pharmacy_user'),
    ]

    operations = [
    ]
