# Generated by Django 4.2.1 on 2023-06-08 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_merge_0010_merge_20230607_1535_0010_pharmacy_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicationintake',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='address',
            field=models.CharField(help_text='Please include City and State', max_length=200),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='phoneNumber',
            field=models.TextField(max_length=25),
        ),
    ]
